version: '2'
services:
  mainDB:
    image: mysql
    container_name: spring-main-db
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci