datasource:
  main:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo?serverTimezone=Asia/Seoul
      username: root
      password: password
    slaves:
      -
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/demo?serverTimezone=Asia/Seoul
        username: root
        password: password
  jpa:
    ddl-auto: none
    show-sql: true
    format-sql: true

operation:
  swagger:
    title: boilerplate
    description: be
    version: 1.0.0
    contact-name: joonseolee
    contact-url: github.com/joonseolee
    contact-email: niceweather94@gmail.com
    ant-pattern: /api/**
